site_name: WebTundra
site_url: https://webtundra.readthedocs.org
repo_url: https://github.com/realXtend/WebTundra
site_description: WebTundra Documentation
docs_dir: doc/
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - Home: index.md
  - 'Installation & Administration Manual': 'installation_administration.md'
  - 'User & Programmers Manual': 'user_programmers.md'
google_analytics: ['UA-83869420-1', 'http://webtundra.readthedocs.io/']